name: apkpribadi
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  # INI ADALAH PERBAIKAN DARI ERROR SEBELUMNYA
  # Pastikan indentasi (spasi) di depannya benar
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Database Lokal
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utility
  intl: ^0.19.0
  path_provider: ^2.1.3
  google_fonts: ^6.2.1
  
  # UI & Ikon
  iconsax_flutter: ^1.0.0
  fl_chart: ^0.68.0
  
  # File Handling
  image_picker: ^1.1.2
  file_picker: ^8.0.5
  open_filex: ^4.4.0 # Ini package baru yang kita tambahkan

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Hive Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.10

flutter:
  uses-material-design: true